name: test

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        go:
          - "1.26"
          - "1.25"
          - "1.24"
        mysql:
          - "9.7"
          - "8.4"
          - "8.0"
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - name: Set up Go
        uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6.5.0
        with:
          go-version: ${{ matrix.go }}

      - name: setup MySQL
        uses: shogo82148/actions-setup-mysql@076e636c45996ec8cb1a455c65f9f5364aeebd8a # v1.52.1
        with:
          mysql-version: ${{ matrix.mysql }}
          root-password: verysecret

      - name: Run tests
        run: |
          go test -v -coverprofile=coverage.txt ./...
        env:
          MYSQLPOOL_USER: root
          MYSQLPOOL_PASS: verysecret
          MYSQLPOOL_HOST: 127.0.0.1
          MYSQLPOOL_PORT: 3306

      - name: Send coverage to codecov.io
        uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f # v7.0.0
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          env_vars: GO
          root_dir: .
        env:
          GO: ${{ matrix.go }}
